# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
env: _R_CHECK_CRAN_INCOMING_=FALSE
cache: packages
jobs:
  include:
  - r: oldrel
  - r: release
  - r: devel
  - os: osx
    r: release
    brew_packages: libgit2
r_binary_packages:
  - covr
warnings_are_errors: false
after_success:
  - Rscript -e 'covr::codecov()'